# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_store
    username: postgres
    password: postgres

# Hibernate Configuration
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

# Server Configuration
server:
  port: 8080
